/**
 * CoenergyGO — Catálogo Técnico de Carregadores de Veículos Elétricos Homologados
 * Modelagem baseada nos manuais oficiais de fabricantes da pasta Downloads:
 * - WEG WEMOB: Easy, Wall, Parking G2, Station (30-80 kW) e Station HPC (160-320 kW)
 * - BENY Electric: Linhas AC BCP e DC Fast Charging BDC (60-180 kW)
 * Cordeiro Energia — Engenharia & Mobilidade Elétrica
 */

import { ChargerDatasheet } from '../coenergygo/types';
export type { ChargerDatasheet };

export const HOMOLOGATED_CHARGERS: ChargerDatasheet[] = [
  // ─── 1. LINHA WEG AC RESIDENCIAL & COMERCIAL ─────────────────────────────
  {
    id: 'weg-wemob-easy-7-4',
    brand: 'WEG',
    model: 'WEMOB Easy 7.4 kW',
    series: 'WEMOB Easy',
    powerKW: 7.4,
    phases: 1,
    voltageV: 220,
    currentInA: 32.0,
    efficiencyPercent: 99.0,
    powerFactor: 0.98,
    thdiPercent: 3.0,
    connectorType: 'Tipo 2',
    connectorsCount: 1,
    coolingType: 'natural',
    ipRating: 'IP54',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: false,
    protocolOCPP: 'N/A (Autônomo Plug&Play / RFID)',
    datasheetPdfUrl: 'WEG-WEMOB-EASY-manual-10011660578-pt.pdf'
  },
  {
    id: 'weg-wemob-wall-7-4',
    brand: 'WEG',
    model: 'WEMOB Wall 7.4 kW Smart',
    series: 'WEMOB Wall',
    powerKW: 7.4,
    phases: 1,
    voltageV: 220,
    currentInA: 32.0,
    efficiencyPercent: 99.0,
    powerFactor: 0.98,
    thdiPercent: 3.0,
    connectorType: 'Tipo 2',
    connectorsCount: 1,
    coolingType: 'natural',
    ipRating: 'IP54',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: false,
    protocolOCPP: 'OCPP 1.6J (Wi-Fi / Ethernet)',
    datasheetPdfUrl: 'WEG-WEMOB-50105757-pt.pdf'
  },
  {
    id: 'weg-wemob-wall-22',
    brand: 'WEG',
    model: 'WEMOB Wall 22 kW Trifásico',
    series: 'WEMOB Wall',
    powerKW: 22.0,
    phases: 3,
    voltageV: 380,
    currentInA: 32.0,
    efficiencyPercent: 99.0,
    powerFactor: 0.98,
    thdiPercent: 3.0,
    connectorType: 'Tipo 2',
    connectorsCount: 1,
    coolingType: 'natural',
    ipRating: 'IP54',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: false,
    protocolOCPP: 'OCPP 1.6J (Wi-Fi / Ethernet / 4G)',
    datasheetPdfUrl: 'WEG-WEMOB-50105757-pt.pdf'
  },
  {
    id: 'weg-wemob-parking-22',
    brand: 'WEG',
    model: 'WEMOB Parking G2 22 kW (Totem Condomínio)',
    series: 'WEMOB Parking',
    powerKW: 22.0,
    phases: 3,
    voltageV: 380,
    currentInA: 32.0,
    efficiencyPercent: 99.0,
    powerFactor: 0.98,
    thdiPercent: 3.0,
    connectorType: 'Tipo 2',
    connectorsCount: 1,
    coolingType: 'natural',
    ipRating: 'IP54',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: true,
    protocolOCPP: 'OCPP 1.6J / 2.0.1 (Ethernet / 4G / Modbus RS485)',
    datasheetPdfUrl: 'WEG-WEMOB-PARKING-G2-63A-guia-de-instalacao-10010005119-pt.pdf'
  },
  {
    id: 'weg-wemob-parking-dual-44',
    brand: 'WEG',
    model: 'WEMOB Parking Dual 44 kW (2x 22 kW)',
    series: 'WEMOB Parking',
    powerKW: 44.0,
    phases: 3,
    voltageV: 380,
    currentInA: 64.0,
    efficiencyPercent: 99.0,
    powerFactor: 0.98,
    thdiPercent: 3.0,
    connectorType: 'Tipo 2 (2 tomadas)',
    connectorsCount: 2,
    coolingType: 'natural',
    ipRating: 'IP54',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: true,
    protocolOCPP: 'OCPP 1.6J / 2.0.1 com DLM dinâmico',
    datasheetPdfUrl: 'WEG-WEMOB-PARKING-G2-63A-guia-de-instalacao-10010005119-pt.pdf'
  },

  // ─── 2. LINHA WEG DC RÁPIDO & ULTRA-RÁPIDO (ELETROPOSTO) ──────────────────
  {
    id: 'weg-wemob-station-30',
    brand: 'WEG',
    model: 'WEMOB Station 30 kW DC Rápido',
    series: 'WEMOB Station',
    powerKW: 30.0,
    phases: 3,
    voltageV: 380,
    currentInA: 47.5,
    efficiencyPercent: 95.5,
    powerFactor: 0.99,
    thdiPercent: 4.8,
    connectorType: 'CCS2',
    connectorsCount: 1,
    coolingType: 'ar_forcado',
    ipRating: 'IP54',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: true,
    protocolOCPP: 'OCPP 1.6J (Ethernet / 4G / Modbus)',
    datasheetPdfUrl: 'WEG-WEMOB-station-ccs-30-40kW-user-manual-10009771417-pt.pdf'
  },
  {
    id: 'weg-wemob-station-60',
    brand: 'WEG',
    model: 'WEMOB Station 60 kW DC Rápido (Dual CCS2)',
    series: 'WEMOB Station',
    powerKW: 60.0,
    phases: 3,
    voltageV: 380,
    currentInA: 95.0,
    efficiencyPercent: 96.0,
    powerFactor: 0.99,
    thdiPercent: 4.2,
    connectorType: '2x CCS2 (ou CCS2 + CHAdeMO)',
    connectorsCount: 2,
    coolingType: 'ar_forcado',
    ipRating: 'IP54',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: true,
    protocolOCPP: 'OCPP 1.6J / 2.0.1 (Smart Charging & DLM)',
    datasheetPdfUrl: 'WEG_WEMOB_10012896098_wcd-ed320-scs_Manual-do-usu-rio-internet.pdf'
  },
  {
    id: 'weg-wemob-station-80',
    brand: 'WEG',
    model: 'WEMOB Station 80 kW DC Rápido',
    series: 'WEMOB Station',
    powerKW: 80.0,
    phases: 3,
    voltageV: 380,
    currentInA: 126.5,
    efficiencyPercent: 96.2,
    powerFactor: 0.99,
    thdiPercent: 4.0,
    connectorType: '2x CCS2',
    connectorsCount: 2,
    coolingType: 'ar_forcado',
    ipRating: 'IP54',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: true,
    protocolOCPP: 'OCPP 1.6J / 2.0.1',
    datasheetPdfUrl: 'WEG_WEMOB_10012896098_wcd-ed320-scs_Manual-do-usu-rio-internet.pdf'
  },
  {
    id: 'weg-wemob-station-120',
    brand: 'WEG',
    model: 'WEMOB Station 120 kW DC Hub',
    series: 'WEMOB Station',
    powerKW: 120.0,
    phases: 3,
    voltageV: 380,
    currentInA: 189.0,
    efficiencyPercent: 96.4,
    powerFactor: 0.99,
    thdiPercent: 3.8,
    connectorType: '2x CCS2 (Dynamic Power Sharing)',
    connectorsCount: 2,
    coolingType: 'ar_forcado',
    ipRating: 'IP55',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: true,
    protocolOCPP: 'OCPP 1.6J / 2.0.1',
    datasheetPdfUrl: 'WEG_WDS_WEMOB_10012843270_station-hpc-manual-do-usu-rio-internet_pt.pdf'
  },
  {
    id: 'weg-wemob-hpc-320',
    brand: 'WEG',
    model: 'WEMOB Station HPC 320 kW Ultra-rápido',
    series: 'WEMOB HPC',
    powerKW: 320.0,
    phases: 3,
    voltageV: 380,
    currentInA: 505.0,
    efficiencyPercent: 96.6,
    powerFactor: 0.99,
    thdiPercent: 3.0,
    connectorType: '2x CCS2 Refrigerados a Líquido (500A)',
    connectorsCount: 2,
    coolingType: 'liquido',
    ipRating: 'IP55',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: true,
    protocolOCPP: 'OCPP 2.0.1 com ISO 15118 Plug&Charge',
    datasheetPdfUrl: 'WEG_WDS_WEMOB_10012843270_station-hpc-manual-do-usu-rio-internet_pt.pdf'
  },

  // ─── 3. LINHA BENY ELECTRIC (AC & DC FAST CHARGING) ──────────────────────
  {
    id: 'beny-bcp-7-4',
    brand: 'BENY',
    model: 'BENY BCP-A2N-L 7.4 kW Smart AC',
    series: 'Linha BCP',
    powerKW: 7.4,
    phases: 1,
    voltageV: 220,
    currentInA: 32.0,
    efficiencyPercent: 99.0,
    powerFactor: 0.98,
    thdiPercent: 3.2,
    connectorType: 'Tipo 2',
    connectorsCount: 1,
    coolingType: 'natural',
    ipRating: 'IP65',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: false,
    protocolOCPP: 'OCPP 1.6J com DLM residencial via TC incluso',
    datasheetPdfUrl: 'BENY Datasheet - PT.pdf'
  },
  {
    id: 'beny-bcp-22',
    brand: 'BENY',
    model: 'BENY BCP-A2N-L 22 kW Trifásico',
    series: 'Linha BCP',
    powerKW: 22.0,
    phases: 3,
    voltageV: 380,
    currentInA: 32.0,
    efficiencyPercent: 99.0,
    powerFactor: 0.98,
    thdiPercent: 3.2,
    connectorType: 'Tipo 2',
    connectorsCount: 1,
    coolingType: 'natural',
    ipRating: 'IP65',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: false,
    protocolOCPP: 'OCPP 1.6J (Wi-Fi/Bluetooth/Ethernet)',
    datasheetPdfUrl: 'BENY Datasheet - PT.pdf'
  },
  {
    id: 'beny-bdc-60',
    brand: 'BENY',
    model: 'BENY BDC-60 kW DC Commercial Fast',
    series: 'Linha BDC',
    powerKW: 60.0,
    phases: 3,
    voltageV: 380,
    currentInA: 95.5,
    efficiencyPercent: 95.5,
    powerFactor: 0.99,
    thdiPercent: 4.5,
    connectorType: '2x CCS2 (ou CCS2 + CHAdeMO)',
    connectorsCount: 2,
    coolingType: 'ar_forcado',
    ipRating: 'IP55',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: true,
    protocolOCPP: 'OCPP 1.6J / 2.0.1 (RFID, Tela 7" Touch, 4G)',
    datasheetPdfUrl: 'Catalog of BENY DC EV Charging Solution 20240330.pdf'
  },
  {
    id: 'beny-bdc-120',
    brand: 'BENY',
    model: 'BENY BDC-120 kW Dual CCS2 Fast Charger',
    series: 'Linha BDC',
    powerKW: 120.0,
    phases: 3,
    voltageV: 380,
    currentInA: 191.0,
    efficiencyPercent: 96.0,
    powerFactor: 0.99,
    thdiPercent: 4.0,
    connectorType: '2x CCS2 (Compartilhamento Dinâmico)',
    connectorsCount: 2,
    coolingType: 'ar_forcado',
    ipRating: 'IP55',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: true,
    protocolOCPP: 'OCPP 1.6J / 2.0.1',
    datasheetPdfUrl: 'Catalog of BENY DC EV Charging Solution 20240330.pdf'
  },
  {
    id: 'beny-bdc-180',
    brand: 'BENY',
    model: 'BENY BDC-180 kW Ultra Fast Station',
    series: 'Linha BDC',
    powerKW: 180.0,
    phases: 3,
    voltageV: 380,
    currentInA: 285.0,
    efficiencyPercent: 96.2,
    powerFactor: 0.99,
    thdiPercent: 3.5,
    connectorType: '2x CCS2 (até 300A por conector)',
    connectorsCount: 2,
    coolingType: 'ar_forcado',
    ipRating: 'IP55',
    ikRating: 'IK10',
    hasBuiltinRDCDD: true,
    hasBuiltinEPO: true,
    protocolOCPP: 'OCPP 2.0.1',
    datasheetPdfUrl: 'Catalog of BENY DC EV Charging Solution 20240330.pdf'
  }
];

export function getChargerById(id: string): ChargerDatasheet | undefined {
  return HOMOLOGATED_CHARGERS.find(c => c.id === id);
}

export function searchChargers(query: string): ChargerDatasheet[] {
  const q = query.toLowerCase().trim();
  if (!q) return HOMOLOGATED_CHARGERS;
  return HOMOLOGATED_CHARGERS.filter(c =>
    c.brand.toLowerCase().includes(q) ||
    c.model.toLowerCase().includes(q) ||
    c.series.toLowerCase().includes(q) ||
    c.connectorType.toLowerCase().includes(q) ||
    c.powerKW.toString().includes(q)
  );
}

export function filterChargersByType(type: 'AC' | 'DC'): ChargerDatasheet[] {
  return HOMOLOGATED_CHARGERS.filter(c => type === 'AC' ? c.powerKW <= 44 && c.voltageV <= 380 && !c.connectorType.includes('CCS') : c.powerKW >= 30 || c.connectorType.includes('CCS'));
}

