
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.7.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
Prisma.prismaVersion = {
  client: "7.7.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  role: 'role',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlanilhaInstalacaoScalarFieldEnum = {
  id: 'id',
  idInterno: 'idInterno',
  instalacao: 'instalacao',
  diaPrev: 'diaPrev',
  manualInstalacao: 'manualInstalacao',
  obsInstalacao: 'obsInstalacao',
  vencimentoParecer: 'vencimentoParecer',
  vencimentoContrato: 'vencimentoContrato',
  automaticoPrevInstala: 'automaticoPrevInstala',
  dataVenda: 'dataVenda',
  statusProtocolo: 'statusProtocolo',
  statusCompra: 'statusCompra',
  inversor: 'inversor',
  numMod: 'numMod',
  modulo: 'modulo',
  cidadeSheet: 'cidadeSheet',
  bairro: 'bairro',
  rua: 'rua',
  numRua: 'numRua',
  telhado: 'telhado',
  telefoneSheet: 'telefoneSheet',
  vendedorSheet: 'vendedorSheet',
  observacao: 'observacao',
  anexoFotos: 'anexoFotos',
  anexoArquivos: 'anexoArquivos',
  dataSolicitacao: 'dataSolicitacao',
  solicitacao: 'solicitacao',
  status: 'status',
  vendedor: 'vendedor',
  telefoneCliente: 'telefoneCliente',
  cidade: 'cidade',
  dataPrevista: 'dataPrevista',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  atividadeExtra: 'atividadeExtra',
  prioridade: 'prioridade',
  telefoneVendedor: 'telefoneVendedor',
  notificadoWhatsapp: 'notificadoWhatsapp'
};

exports.Prisma.TarifasScalarFieldEnum = {
  id: 'id',
  distribuidora: 'distribuidora',
  subGrupo: 'subGrupo',
  modalidade: 'modalidade',
  postoTarifario: 'postoTarifario',
  valorTUSD: 'valorTUSD',
  valorTE: 'valorTE',
  dataInicio: 'dataInicio',
  resolution: 'resolution',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StatusOptionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  color: 'color',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SystemSettingsScalarFieldEnum = {
  id: 'id',
  limiteVerde: 'limiteVerde',
  limiteAmarelo: 'limiteAmarelo',
  limiteParecer: 'limiteParecer',
  updatedAt: 'updatedAt'
};

exports.Prisma.CarregadorScalarFieldEnum = {
  id: 'id',
  brand: 'brand',
  model: 'model',
  power: 'power',
  voltage: 'voltage',
  phases: 'phases',
  current: 'current',
  connectorType: 'connectorType',
  protectionReq: 'protectionReq',
  groundingReq: 'groundingReq',
  datasheetUrl: 'datasheetUrl',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjetoDimensionamentoScalarFieldEnum = {
  id: 'id',
  projectName: 'projectName',
  clientName: 'clientName',
  utility: 'utility',
  entranceCategory: 'entranceCategory',
  distance: 'distance',
  installationMethod: 'installationMethod',
  chargerId: 'chargerId',
  calculatedCurrent: 'calculatedCurrent',
  calculatedCableGauge: 'calculatedCableGauge',
  calculatedBreaker: 'calculatedBreaker',
  calculatedDR: 'calculatedDR',
  calculatedConduit: 'calculatedConduit',
  voltageDrop: 'voltageDrop',
  groundingAnalysis: 'groundingAnalysis',
  isServiceEntranceOk: 'isServiceEntranceOk',
  analysisNotes: 'analysisNotes',
  hasTransformer: 'hasTransformer',
  transformerPrimaryVoltage: 'transformerPrimaryVoltage',
  transformerSecondaryVoltage: 'transformerSecondaryVoltage',
  transformerDistance: 'transformerDistance',
  chargerDistance: 'chargerDistance',
  groundingType: 'groundingType',
  calculatedPrimaryCable: 'calculatedPrimaryCable',
  calculatedPrimaryBreaker: 'calculatedPrimaryBreaker',
  calculatedDPS: 'calculatedDPS',
  calculatedIDR: 'calculatedIDR',
  fireExtinguisherType: 'fireExtinguisherType',
  hasEmergencyButton5m: 'hasEmergencyButton5m',
  requiresWarningSigns: 'requiresWarningSigns',
  fireDeptStandards: 'fireDeptStandards',
  abntStandards: 'abntStandards',
  specificSafetyNotes: 'specificSafetyNotes',
  existingLoadKW: 'existingLoadKW',
  simultaneityFactor: 'simultaneityFactor',
  isCollective: 'isCollective',
  location: 'location',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EngeProjetoScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  cliente: 'cliente',
  tipo: 'tipo',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  levantamentoCargas: 'levantamentoCargas'
};

exports.Prisma.AnaliseFaturaScalarFieldEnum = {
  id: 'id',
  projetoId: 'projetoId',
  nomeCliente: 'nomeCliente',
  endereco: 'endereco',
  concessionaria: 'concessionaria',
  numeroInstalacao: 'numeroInstalacao',
  cnpjCpfTitular: 'cnpjCpfTitular',
  grupoTarifario: 'grupoTarifario',
  subgrupo: 'subgrupo',
  modalidadeTarifaria: 'modalidadeTarifaria',
  classeConsumo: 'classeConsumo',
  consumoMeses: 'consumoMeses',
  consumoMedioMensalKWh: 'consumoMedioMensalKWh',
  consumoTotalAnualKWh: 'consumoTotalAnualKWh',
  demandaContratadaKW: 'demandaContratadaKW',
  demandaMedidaHPKW: 'demandaMedidaHPKW',
  demandaMedidaHFPKW: 'demandaMedidaHFPKW',
  temGeracao: 'temGeracao',
  geracaoTipos: 'geracaoTipos',
  geracaoInjetadaKWh: 'geracaoInjetadaKWh',
  tusd: 'tusd',
  te: 'te',
  tarifaHP: 'tarifaHP',
  tarifaHFP: 'tarifaHFP',
  tarifaDemandaHP: 'tarifaDemandaHP',
  tarifaDemandaHFP: 'tarifaDemandaHFP',
  valorUltimaFatura: 'valorUltimaFatura',
  bandeiraTarifaria: 'bandeiraTarifaria',
  rawPdfUrl: 'rawPdfUrl',
  extraidoPorIA: 'extraidoPorIA',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  padraoConexao: 'padraoConexao',
  descontoIrrigante: 'descontoIrrigante',
  energiaAtivaHRKWh: 'energiaAtivaHRKWh',
  mesReferencia: 'mesReferencia',
  vencimento: 'vencimento'
};

exports.Prisma.AnaliseMassaDadosScalarFieldEnum = {
  id: 'id',
  projetoId: 'projetoId',
  rawXlsUrls: 'rawXlsUrls',
  nomeArquivos: 'nomeArquivos',
  postoHP_inicio: 'postoHP_inicio',
  postoHP_fim: 'postoHP_fim',
  postoHFP_inicio: 'postoHFP_inicio',
  postoHFP_fim: 'postoHFP_fim',
  postoHR_inicio: 'postoHR_inicio',
  postoHR_fim: 'postoHR_fim',
  diasUteisSemana: 'diasUteisSemana',
  periodoInicio: 'periodoInicio',
  periodoFim: 'periodoFim',
  totalRegistros: 'totalRegistros',
  maxDemandaHP: 'maxDemandaHP',
  maxDemandaHFP: 'maxDemandaHFP',
  maxDemandaHR: 'maxDemandaHR',
  maxDemandaTotal: 'maxDemandaTotal',
  consumoHP_kWh: 'consumoHP_kWh',
  consumoHFP_kWh: 'consumoHFP_kWh',
  consumoHR_kWh: 'consumoHR_kWh',
  curvaMediaDiaria: 'curvaMediaDiaria',
  curvaHP: 'curvaHP',
  curvaHFP: 'curvaHFP',
  diaCriticoData: 'diaCriticoData',
  diaCriticoDemandaKW: 'diaCriticoDemandaKW',
  diaCriticoCurva: 'diaCriticoCurva',
  mediaDiaCritico: 'mediaDiaCritico',
  maxDemandaTotalData: 'maxDemandaTotalData',
  minDemandaTotal: 'minDemandaTotal',
  minDemandaTotalData: 'minDemandaTotalData',
  processado: 'processado',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InversorSolarScalarFieldEnum = {
  id: 'id',
  fabricante: 'fabricante',
  modelo: 'modelo',
  potenciaNominalKW: 'potenciaNominalKW',
  tipoConexao: 'tipoConexao',
  tensaoEntradaMinV: 'tensaoEntradaMinV',
  tensaoEntradaMaxV: 'tensaoEntradaMaxV',
  correnteMaxCC: 'correnteMaxCC',
  numeroStringsMPPT: 'numeroStringsMPPT',
  potenciaMPPTKW: 'potenciaMPPTKW',
  tensaoSaidaVAC: 'tensaoSaidaVAC',
  fatorPotencia: 'fatorPotencia',
  eficiencia: 'eficiencia',
  comunicacao: 'comunicacao',
  ipBD: 'ipBD',
  datasheetUrl: 'datasheetUrl',
  ieee1547Compliant: 'ieee1547Compliant',
  responseTimeMs: 'responseTimeMs',
  thdMax: 'thdMax',
  powerFactorControl: 'powerFactorControl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  fase: 'fase'
};

exports.Prisma.ModuloFotovoltaicoScalarFieldEnum = {
  id: 'id',
  fabricante: 'fabricante',
  modelo: 'modelo',
  potenciaPicoWp: 'potenciaPicoWp',
  Vmp: 'Vmp',
  Imp: 'Imp',
  Voc: 'Voc',
  Isc: 'Isc',
  eficiencia: 'eficiencia',
  dimensoes: 'dimensoes',
  pesoKg: 'pesoKg',
  coefTempVoc: 'coefTempVoc',
  coefTempIsc: 'coefTempIsc',
  garantiaAnos: 'garantiaAnos',
  datasheetUrl: 'datasheetUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BateriaSistemaScalarFieldEnum = {
  id: 'id',
  fabricante: 'fabricante',
  modelo: 'modelo',
  tecnologia: 'tecnologia',
  capacidadeNomKWh: 'capacidadeNomKWh',
  tensaoNominalV: 'tensaoNominalV',
  profundidadeDescarga: 'profundidadeDescarga',
  ciclosVida: 'ciclosVida',
  correnteMaxCarga: 'correnteMaxCarga',
  correnteMaxDescarga: 'correnteMaxDescarga',
  tempOperacaoMin: 'tempOperacaoMin',
  tempOperacaoMax: 'tempOperacaoMax',
  roundTripEfficiency: 'roundTripEfficiency',
  standbyLossesKW: 'standbyLossesKW',
  thermalBufferLower: 'thermalBufferLower',
  thermalBufferUpper: 'thermalBufferUpper',
  datasheetUrl: 'datasheetUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EstruturaFotovoltaicaScalarFieldEnum = {
  id: 'id',
  fabricante: 'fabricante',
  modelo: 'modelo',
  tipoTelhado: 'tipoTelhado',
  materialEstrutura: 'materialEstrutura',
  cargaMaxVentoKNm2: 'cargaMaxVentoKNm2',
  modulosMaxFileira: 'modulosMaxFileira',
  anguloMin: 'anguloMin',
  anguloMax: 'anguloMax',
  datasheetUrl: 'datasheetUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EstudoBESSScalarFieldEnum = {
  id: 'id',
  projetoId: 'projetoId',
  demandaAlvoKW: 'demandaAlvoKW',
  estrategia: 'estrategia',
  bateriaId: 'bateriaId',
  inversorId: 'inversorId',
  quantidadeBaterias: 'quantidadeBaterias',
  picoReduzidoKW: 'picoReduzidoKW',
  economiaMensalLeve: 'economiaMensalLeve',
  economiaMensalBESS: 'economiaMensalBESS',
  paybackSimples: 'paybackSimples',
  vpl: 'vpl',
  tir: 'tir',
  configSimulacao: 'configSimulacao',
  resultadosGrafico: 'resultadosGrafico',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EstudoSolarScalarFieldEnum = {
  id: 'id',
  projetoId: 'projetoId',
  lat: 'lat',
  long: 'long',
  hspManual: 'hspManual',
  hspPvgis: 'hspPvgis',
  tilt: 'tilt',
  azimuth: 'azimuth',
  pr: 'pr',
  perdaSistema: 'perdaSistema',
  geracaoAlvoKWh: 'geracaoAlvoKWh',
  potenciaNecessariaKWp: 'potenciaNecessariaKWp',
  moduloId: 'moduloId',
  inversorId: 'inversorId',
  quantidadeModulos: 'quantidadeModulos',
  quantidadeInversores: 'quantidadeInversores',
  numStrings: 'numStrings',
  modulosPorString: 'modulosPorString',
  areaOcupadaM2: 'areaOcupadaM2',
  pesoTotalKg: 'pesoTotalKg',
  investimentoEstimado: 'investimentoEstimado',
  paybackAnos: 'paybackAnos',
  vpl: 'vpl',
  tir: 'tir',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  inversoresSugeridos: 'inversoresSugeridos',
  overEnclosureAlvo: 'overEnclosureAlvo'
};

exports.Prisma.UsinaFotovoltaicaScalarFieldEnum = {
  id: 'id',
  projetoId: 'projetoId',
  nome: 'nome',
  localizacao: 'localizacao'
};

exports.Prisma.EquipamentoUsinaScalarFieldEnum = {
  id: 'id',
  usinaId: 'usinaId',
  nome: 'nome',
  tag: 'tag',
  localizacao: 'localizacao',
  criticidade: 'criticidade',
  periodicidadeDias: 'periodicidadeDias',
  fotoBase64: 'fotoBase64',
  anexos: 'anexos'
};

exports.Prisma.ManutencaoUsinaScalarFieldEnum = {
  id: 'id',
  usinaId: 'usinaId',
  equipamentoId: 'equipamentoId',
  tipo: 'tipo',
  dataAgendada: 'dataAgendada',
  dataRealizada: 'dataRealizada',
  status: 'status',
  descricao: 'descricao',
  pecasTrocadas: 'pecasTrocadas',
  custoMateriais: 'custoMateriais',
  custoMaoDeObra: 'custoMaoDeObra',
  tempoInicio: 'tempoInicio',
  tempoFim: 'tempoFim',
  fotosUrls: 'fotosUrls',
  fotosDetalhes: 'fotosDetalhes',
  documentosUrls: 'documentosUrls',
  responsavel: 'responsavel',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ComissionamentoUsinaScalarFieldEnum = {
  id: 'id',
  usinaId: 'usinaId',
  tipo: 'tipo',
  data: 'data',
  responsavel: 'responsavel',
  crea: 'crea',
  profissionalId: 'profissionalId',
  numero: 'numero',
  status: 'status',
  dadosTecnicos: 'dadosTecnicos',
  observacoes: 'observacoes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProfissionalScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  telefone: 'telefone',
  email: 'email',
  crea: 'crea',
  observacao: 'observacao',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RelatorioTermografiaScalarFieldEnum = {
  id: 'id',
  usinaId: 'usinaId',
  profissionalId: 'profissionalId',
  dataInspecao: 'dataInspecao',
  equipamentoCamera: 'equipamentoCamera',
  temperaturaAmbiente: 'temperaturaAmbiente',
  irradiacao: 'irradiacao',
  velocidadeVento: 'velocidadeVento',
  umidadeRelativa: 'umidadeRelativa',
  emissividade: 'emissividade',
  distanciaRef: 'distanciaRef',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ItemTermografiaScalarFieldEnum = {
  id: 'id',
  relatorioId: 'relatorioId',
  tipoEquipamento: 'tipoEquipamento',
  tag: 'tag',
  localizacao: 'localizacao',
  temperaturaMedida: 'temperaturaMedida',
  temperaturaReferencia: 'temperaturaReferencia',
  deltaT: 'deltaT',
  severidade: 'severidade',
  causaProvavel: 'causaProvavel',
  recomendacao: 'recomendacao',
  imagemTermicaUrl: 'imagemTermicaUrl',
  imagemVisualUrl: 'imagemVisualUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  User: 'User',
  PlanilhaInstalacao: 'PlanilhaInstalacao',
  Tarifas: 'Tarifas',
  StatusOption: 'StatusOption',
  SystemSettings: 'SystemSettings',
  Carregador: 'Carregador',
  ProjetoDimensionamento: 'ProjetoDimensionamento',
  EngeProjeto: 'EngeProjeto',
  AnaliseFatura: 'AnaliseFatura',
  AnaliseMassaDados: 'AnaliseMassaDados',
  InversorSolar: 'InversorSolar',
  ModuloFotovoltaico: 'ModuloFotovoltaico',
  BateriaSistema: 'BateriaSistema',
  EstruturaFotovoltaica: 'EstruturaFotovoltaica',
  EstudoBESS: 'EstudoBESS',
  EstudoSolar: 'EstudoSolar',
  UsinaFotovoltaica: 'UsinaFotovoltaica',
  EquipamentoUsina: 'EquipamentoUsina',
  ManutencaoUsina: 'ManutencaoUsina',
  ComissionamentoUsina: 'ComissionamentoUsina',
  Profissional: 'Profissional',
  RelatorioTermografia: 'RelatorioTermografia',
  ItemTermografia: 'ItemTermografia'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
